// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

// Ayah defines model for Ayah.
type Ayah struct {
	Ar            *string `json:"ar,omitempty"`
	AudioUrl      *string `json:"audio_url,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	Id            *int    `json:"id,omitempty"`
	Idn           *string `json:"idn,omitempty"`
	Number        *int    `json:"number,omitempty"`
	NumberInSurah *int    `json:"number_in_surah,omitempty"`
	Page          *int    `json:"page,omitempty"`
	SurahNumber   *int    `json:"surah_number,omitempty"`
	Tr            *string `json:"tr,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Page defines model for Page.
type Page struct {
	ListAyah  *[]Ayah  `json:"list_ayah,omitempty"`
	ListSurah *[]Surah `json:"list_surah,omitempty"`
	PageId    *int     `json:"page_id,omitempty"`
}

// Surah defines model for Surah.
type Surah struct {
	Ar        *string `json:"ar,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Id        *int    `json:"id,omitempty"`
	Idn       *string `json:"idn,omitempty"`
	Number    *int    `json:"number,omitempty"`
	Page      *int    `json:"page,omitempty"`
	TotalAyah *int    `json:"total_ayah,omitempty"`
	Tr        *string `json:"tr,omitempty"`
	Type      *string `json:"type,omitempty"`
}

// PostQuranJSONBody defines parameters for PostQuran.
type PostQuranJSONBody struct {
	ListAyah  *[]Ayah  `json:"list_ayah,omitempty"`
	ListSurah *[]Surah `json:"list_surah,omitempty"`
	PageId    *int     `json:"page_id,omitempty"`
}

// PostQuranJSONRequestBody defines body for PostQuran for application/json ContentType.
type PostQuranJSONRequestBody PostQuranJSONBody
